## YAML Template.
---
name: RPGMaker
main: com.RPGMakerDev.RPGMaker.RPGMaker
version: v1_0_0R1
commands:
    rpgmaker:
        description: Plugin information about RPGMaker
        usage: /rpgmaker
        permission: rpgmaker.info
        permission-message: You do not have permission to use this command